#!/bin/bash
set -e

GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o mdmdirector-linux
GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o mdmdirector-linux-arm64
GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o mdmdirector-darwin
GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o mdmdirector-darwin-arm64
