package ddm

import "strings"

// Declaration type constants
const (
	TypeLegacyProfile    = "com.apple.configuration.legacy"
	TypeActivationSimple = "com.apple.activation.simple"
	TypePackage          = "com.apple.configuration.package"
)

// Declaration top-level class labels (for metrics)
const (
	DeclClassConfiguration = "configuration"
	DeclClassActivation    = "activation"
	DeclClassAsset         = "asset"
	DeclClassManagement    = "management"
	DeclClassUnknown       = "unknown"
)

// Declaration configuration sub-type labels (for metrics)
const (
	DeclSubtypeProfile     = "profile"
	DeclSubtypeApplication = "application"
)

// ClassifyDeclarationType maps a declaration's Type string (e.g. "com.apple.configuration.legacy") to a top-level class and an optional sub-type for metrics labels
func ClassifyDeclarationType(declType string) (class, subtype string) {
	switch declType {
	case TypeLegacyProfile:
		return DeclClassConfiguration, DeclSubtypeProfile
	case TypePackage:
		return DeclClassConfiguration, DeclSubtypeApplication
	case TypeActivationSimple:
		return DeclClassActivation, ""
	}

	switch {
	case strings.HasPrefix(declType, "com.apple.configuration."):
		return DeclClassConfiguration, ""
	case strings.HasPrefix(declType, "com.apple.activation."):
		return DeclClassActivation, ""
	case strings.HasPrefix(declType, "com.apple.asset."):
		return DeclClassAsset, ""
	case strings.HasPrefix(declType, "com.apple.management."):
		return DeclClassManagement, ""
	}

	return DeclClassUnknown, ""
}

// ClassifyDeclarationID maps a declaration identifier (e.g. "<prefix>.<udid>.legacy_profile.<id>") to same (class, subtype)
func ClassifyDeclarationID(identifier string) (class, subtype string) {
	switch {
	case strings.Contains(identifier, ".legacy_profile_activation."):
		return DeclClassActivation, ""
	case strings.Contains(identifier, ".legacy_profile."):
		return DeclClassConfiguration, DeclSubtypeProfile
	case strings.Contains(identifier, ".package_activation."):
		return DeclClassActivation, ""
	case strings.Contains(identifier, ".package."):
		return DeclClassConfiguration, DeclSubtypeApplication
	}
	return DeclClassUnknown, ""
}

// Declaration represents a KMFDDM declaration object
// ServerToken is auto-generated by KMFDDM and should be omitted when creating declarations
type Declaration struct {
	Identifier  string      `json:"Identifier"`
	Type        string      `json:"Type"`
	Payload     interface{} `json:"Payload"`
	ServerToken string      `json:"ServerToken,omitempty"`
}

// LegacyProfilePayload is the Payload for a com.apple.configuration.legacy declaration
type LegacyProfilePayload struct {
	ProfileURL string `json:"ProfileURL"`
}

// ActivationSimplePayload is the Payload for a com.apple.activation.simple declaration
type ActivationSimplePayload struct {
	StandardConfigurations []string `json:"StandardConfigurations"`
}

// PackagePayload is the Payload for a com.apple.configuration.package declaration
type PackagePayload struct {
	ManifestURL     string                 `json:"ManifestURL"`
	InstallBehavior PackageInstallBehavior `json:"InstallBehavior"`
}

// PackageInstallBehavior controls how the device installs the package.
// Install: "Required" → auto-install after activation.
// Install: "Optional" → stage as available, user-triggered install.
type PackageInstallBehavior struct {
	Install string `json:"Install"`
}
