package ddm

// Declaration type constants
const (
	TypeLegacyProfile    = "com.apple.configuration.legacy"
	TypeActivationSimple = "com.apple.activation.simple"
	TypePackage          = "com.apple.configuration.management.package"
)

// Declaration represents a KMFDDM declaration object
// ServerToken is auto-generated by KMFDDM and should be omitted when creating declarations
type Declaration struct {
	Identifier  string      `json:"Identifier"`
	Type        string      `json:"Type"`
	Payload     interface{} `json:"Payload"`
	ServerToken string      `json:"ServerToken,omitempty"`
}

// LegacyProfilePayload is the Payload for a com.apple.configuration.legacy declaration
type LegacyProfilePayload struct {
	ProfileURL string `json:"ProfileURL"`
}

// ActivationSimplePayload is the Payload for a com.apple.activation.simple declaration
type ActivationSimplePayload struct {
	StandardConfigurations []string `json:"StandardConfigurations"`
}

// PackagePayload is the Payload for a com.apple.configuration.management.package declaration
type PackagePayload struct {
	ManifestURL string `json:"ManifestURL"`
}
