#!/bin/bash
# The following deletes an MDM profile across all devices registered on micromdm
# Example:
#          ./tools/delete_shared_profile $path_to_profile_on_disk
#
source $MDMDIRECTOR_ENV_PATH
endpoint="profile"
jq -n \
  --arg payload_identifier "$1" \
  '.udids = ["*"]
  |.profiles[0].payload_identifier = $payload_identifier
  |.metadata = true
  |.push_now = true
  '|\
  curl -u "mdmdirector:$API_TOKEN" -X DELETE "$SERVER_URL/$endpoint" -d@-