#!/bin/bash

endpoint="http://localhost:8000/profile"
jq -n \
  --arg udid "$1" \
  --arg payload_identifier "$2" \
  --arg identifier "$3" \
  '.udids = [$udid]
  |.profiles[0].payload_identifier = $payload_identifier
  |.metadata = true
  |.push_now = true
  '|\
  curl -u "mdmdirector:secret" -X DELETE "$endpoint" -d@-

  # |.profiles[0].payload_identifier = $payload_identifier