#!/bin/bash
# Configure Device lock on a device registered in micromdm by a given device by UDID with a supplied locking pincode
# Example:
#          ./tools/device_lock $udid $pincode
#
source $MDMDIRECTOR_ENV_PATH
endpoint="device/command/device_lock"
jq -n \
  --arg udid "$1" \
  --arg pincode "$2" \
  '.udids = [$udid]
  |.value = true
  |.push_now = true
  |.pin = $pincode
  '|\
  curl -u "mdmdirector:$API_TOKEN" -X POST "$SERVER_URL/$endpoint" -d@-
