#!/bin/bash

endpoint="http://localhost:8000/profile"
jq -n \
  --arg udid "$1" \
  --arg payload "$(cat "$2"|openssl base64 -A)" \
  '.udids = [$udid]
  |.profiles = [$payload]
  |.metadata = true
  |.push_now = true
  '|\
  curl -u "mdmdirector:secret" -X POST "$endpoint" -d@-
