#!/bin/bash
# The following applies a MDM profile to a given device registered on micromdm by UDID 
# Example:
#          ./tools/post_profile $deivce_udid $path_to_profile_on_disk
#
source $MDMDIRECTOR_ENV_PATH
endpoint="profile"
jq -n \
  --arg udid "$1" \
  --arg payload "$(cat "$2"|openssl base64 -A)" \
  '.udids = [$udid]
  |.profiles = [$payload]
  |.metadata = true
  |.push_now = true
  '|\
  curl -u "mdmdirector:$API_TOKEN" -X POST "$SERVER_URL/$endpoint" -d@-
