#!/bin/bash

endpoint="https://***REMOVED***/installapplication"
jq -n \
  --arg manifesturl "$1" \
  '.udids = ["*"]
  |.manifest_urls[0].url = $manifesturl
  |.manifest_urls[0].bootstrap_only = true
  '|\
  curl -v -u "mdmdirector:***REMOVED***" -X POST "$endpoint" -d@-
