#!/bin/bash
# The following installs an application based on an install manifest across all devices registers on micromdm 
# Example:
#          ./tools/post_shared_profile $manifest_url
#
source $MDMDIRECTOR_ENV_PATH
endpoint="installapplication"
jq -n \
  --arg manifesturl "$1" \
  '.udids = ["*"]
  |.manifest_urls[0].url = $manifesturl
  |.manifest_urls[0].bootstrap_only = true
  '|\
  curl -u "mdmdirector:$API_TOKEN" -X DELETE "$SERVER_URL/$endpoint" -d@-
