#!/bin/bash

endpoint="http://localhost:8000/installapplication"
jq -n \
  --arg manifesturl "$1" \
  '.udids = ["*"]
  |.manifest_urls[0].url = $manifesturl
  |.manifest_urls[0].bootstrap_only = "true"
  '|\
  curl -X POST "$endpoint" -d@-
