#!/bin/bash

endpoint="http://localhost:8000/installapplication"
jq -n \
  --arg udid "$1" \
  --arg manifesturl "$2" \
  '.udids = [$udid]
  |.manifest_urls[0].url = $manifesturl
  |.manifest_urls[0].bootstrap_only = false
  '|\
  curl -u "mdmdirector:secret" -X POST "$endpoint" -d@-
