#!/bin/bash

endpoint="http://localhost:8000/device/command/erase_device"
jq -n \
  --arg udid "$1" \
  '.udids = [$udid]
  |.value = false
  |.push_now = true
  '|\
  curl -u "mdmdirector:secret" -X POST "$endpoint" -d@-
