on:
  release:
    types: [published]
name: Handle Release
jobs:
  upload:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Build
        run: ./.github/build
      - name: Upload
        run: gh release upload "$TAG" mdmdirector-linux mdmdirector-darwin --clobber
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
